# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI\MyPlotMainWindowUI.ui'
#
# Created: Tue Aug 02 11:09:16 2016
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1137, 906)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("DESIGN_Resource/plot.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayoutPlot = QtGui.QGridLayout()
        self.gridLayoutPlot.setObjectName(_fromUtf8("gridLayoutPlot"))
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayoutPlot.addWidget(self.label, 0, 0, 1, 1)
        self.MessageBoard = QtGui.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MessageBoard.sizePolicy().hasHeightForWidth())
        self.MessageBoard.setSizePolicy(sizePolicy)
        self.MessageBoard.setMinimumSize(QtCore.QSize(250, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(252, 255, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 255, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.MessageBoard.setPalette(palette)
        self.MessageBoard.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.MessageBoard.setCenterOnScroll(False)
        self.MessageBoard.setObjectName(_fromUtf8("MessageBoard"))
        self.gridLayoutPlot.addWidget(self.MessageBoard, 1, 0, 1, 1)
        self.pushButton_ClearMessageBoard = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ClearMessageBoard.sizePolicy().hasHeightForWidth())
        self.pushButton_ClearMessageBoard.setSizePolicy(sizePolicy)
        self.pushButton_ClearMessageBoard.setObjectName(_fromUtf8("pushButton_ClearMessageBoard"))
        self.gridLayoutPlot.addWidget(self.pushButton_ClearMessageBoard, 2, 0, 1, 1)
        self.label_64 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.gridLayoutPlot.addWidget(self.label_64, 3, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayoutPlot)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.comboBox_TempSep = QtGui.QComboBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_TempSep.setFont(font)
        self.comboBox_TempSep.setObjectName(_fromUtf8("comboBox_TempSep"))
        self.comboBox_TempSep.addItem(_fromUtf8(""))
        self.comboBox_TempSep.addItem(_fromUtf8(""))
        self.comboBox_TempSep.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.comboBox_TempSep, 5, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_8.addWidget(self.label_7, 5, 0, 1, 1)
        self.pushButton_TempClearAll = QtGui.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_TempClearAll.setFont(font)
        self.pushButton_TempClearAll.setObjectName(_fromUtf8("pushButton_TempClearAll"))
        self.gridLayout_8.addWidget(self.pushButton_TempClearAll, 2, 8, 1, 1)
        self.spinBox_SkipRowTemp = QtGui.QSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_SkipRowTemp.sizePolicy().hasHeightForWidth())
        self.spinBox_SkipRowTemp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_SkipRowTemp.setFont(font)
        self.spinBox_SkipRowTemp.setProperty("value", 1)
        self.spinBox_SkipRowTemp.setObjectName(_fromUtf8("spinBox_SkipRowTemp"))
        self.gridLayout_8.addWidget(self.spinBox_SkipRowTemp, 5, 3, 1, 1)
        self.pushButton_RemoveTempFiles = QtGui.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_RemoveTempFiles.setFont(font)
        self.pushButton_RemoveTempFiles.setObjectName(_fromUtf8("pushButton_RemoveTempFiles"))
        self.gridLayout_8.addWidget(self.pushButton_RemoveTempFiles, 1, 8, 1, 1)
        self.pushButton_LoadTempFiles = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_LoadTempFiles.setObjectName(_fromUtf8("pushButton_LoadTempFiles"))
        self.gridLayout_8.addWidget(self.pushButton_LoadTempFiles, 0, 8, 1, 1)
        self.spinBox_TempNumber = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_TempNumber.setMinimum(1)
        self.spinBox_TempNumber.setProperty("value", 1)
        self.spinBox_TempNumber.setObjectName(_fromUtf8("spinBox_TempNumber"))
        self.gridLayout_8.addWidget(self.spinBox_TempNumber, 5, 5, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_8.addWidget(self.label_31, 5, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_8.addWidget(self.label_5, 5, 4, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_8.addWidget(self.label_17, 5, 6, 1, 1)
        self.spinBox_TimeCorrection = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_TimeCorrection.setMinimum(-99)
        self.spinBox_TimeCorrection.setObjectName(_fromUtf8("spinBox_TimeCorrection"))
        self.gridLayout_8.addWidget(self.spinBox_TimeCorrection, 5, 7, 1, 1)
        self.listWidget_InputTemp = QtGui.QListWidget(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.listWidget_InputTemp.setFont(font)
        self.listWidget_InputTemp.setObjectName(_fromUtf8("listWidget_InputTemp"))
        self.gridLayout_8.addWidget(self.listWidget_InputTemp, 0, 0, 5, 8)
        self.pushButton_FilesFormat_Term = QtGui.QPushButton(self.groupBox_3)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("DESIGN_Resource/Infobox_info_icon.svg.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_FilesFormat_Term.setIcon(icon1)
        self.pushButton_FilesFormat_Term.setObjectName(_fromUtf8("pushButton_FilesFormat_Term"))
        self.gridLayout_8.addWidget(self.pushButton_FilesFormat_Term, 5, 8, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.pushButton_RemoveFBGFiles = QtGui.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_RemoveFBGFiles.setFont(font)
        self.pushButton_RemoveFBGFiles.setObjectName(_fromUtf8("pushButton_RemoveFBGFiles"))
        self.gridLayout_5.addWidget(self.pushButton_RemoveFBGFiles, 1, 7, 1, 1)
        self.pushButton_LoadFBGFiles = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_LoadFBGFiles.setObjectName(_fromUtf8("pushButton_LoadFBGFiles"))
        self.gridLayout_5.addWidget(self.pushButton_LoadFBGFiles, 0, 7, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 5, 4, 1, 1)
        self.pushButton_FBGClearAll = QtGui.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_FBGClearAll.setFont(font)
        self.pushButton_FBGClearAll.setObjectName(_fromUtf8("pushButton_FBGClearAll"))
        self.gridLayout_5.addWidget(self.pushButton_FBGClearAll, 2, 7, 1, 1)
        self.spinBox_FBGNumber = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_FBGNumber.setMinimum(1)
        self.spinBox_FBGNumber.setProperty("value", 1)
        self.spinBox_FBGNumber.setObjectName(_fromUtf8("spinBox_FBGNumber"))
        self.gridLayout_5.addWidget(self.spinBox_FBGNumber, 5, 5, 1, 1)
        self.label_30 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_5.addWidget(self.label_30, 5, 2, 1, 1)
        self.spinBox_SkipRowFBG = QtGui.QSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_SkipRowFBG.sizePolicy().hasHeightForWidth())
        self.spinBox_SkipRowFBG.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_SkipRowFBG.setFont(font)
        self.spinBox_SkipRowFBG.setProperty("value", 2)
        self.spinBox_SkipRowFBG.setObjectName(_fromUtf8("spinBox_SkipRowFBG"))
        self.gridLayout_5.addWidget(self.spinBox_SkipRowFBG, 5, 3, 1, 1)
        self.comboBox_FBGSep = QtGui.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_FBGSep.setFont(font)
        self.comboBox_FBGSep.setObjectName(_fromUtf8("comboBox_FBGSep"))
        self.comboBox_FBGSep.addItem(_fromUtf8(""))
        self.comboBox_FBGSep.addItem(_fromUtf8(""))
        self.comboBox_FBGSep.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.comboBox_FBGSep, 5, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 5, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 5, 6, 1, 1)
        self.listWidget_InputFBG = QtGui.QListWidget(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.listWidget_InputFBG.setFont(font)
        self.listWidget_InputFBG.setObjectName(_fromUtf8("listWidget_InputFBG"))
        self.gridLayout_5.addWidget(self.listWidget_InputFBG, 0, 0, 5, 7)
        self.pushButton_FilesFormat_FBG = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_FilesFormat_FBG.setIcon(icon1)
        self.pushButton_FilesFormat_FBG.setObjectName(_fromUtf8("pushButton_FilesFormat_FBG"))
        self.gridLayout_5.addWidget(self.pushButton_FilesFormat_FBG, 5, 7, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 0, 1, 3)
        self.label_3 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.pushButton_DataSync = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_DataSync.setObjectName(_fromUtf8("pushButton_DataSync"))
        self.gridLayout_6.addWidget(self.pushButton_DataSync, 0, 0, 1, 1)
        self.progressBar_sync = QtGui.QProgressBar(self.groupBox_4)
        self.progressBar_sync.setProperty("value", 0)
        self.progressBar_sync.setObjectName(_fromUtf8("progressBar_sync"))
        self.gridLayout_6.addWidget(self.progressBar_sync, 0, 1, 1, 1)
        self.pushButton_SaveSyncData = QtGui.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_SaveSyncData.setFont(font)
        self.pushButton_SaveSyncData.setObjectName(_fromUtf8("pushButton_SaveSyncData"))
        self.gridLayout_6.addWidget(self.pushButton_SaveSyncData, 0, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_10.addWidget(self.label_8, 0, 0, 1, 3)
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_10.addWidget(self.label_9, 0, 3, 1, 1)
        self.listWidget_SelectFBG = QtGui.QListWidget(self.groupBox_5)
        self.listWidget_SelectFBG.setObjectName(_fromUtf8("listWidget_SelectFBG"))
        self.gridLayout_10.addWidget(self.listWidget_SelectFBG, 1, 0, 3, 3)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_6.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_12 = QtGui.QLabel(self.groupBox_6)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_12.addWidget(self.label_12, 0, 0, 1, 1)
        self.lineEdit_PhotoElastic = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_PhotoElastic.setObjectName(_fromUtf8("lineEdit_PhotoElastic"))
        self.gridLayout_12.addWidget(self.lineEdit_PhotoElastic, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_6)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_12.addWidget(self.label_10, 1, 0, 2, 1)
        self.lineEdit_ThermalExpansion = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_ThermalExpansion.setObjectName(_fromUtf8("lineEdit_ThermalExpansion"))
        self.gridLayout_12.addWidget(self.lineEdit_ThermalExpansion, 1, 1, 2, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_6)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_12.addWidget(self.label_11, 3, 0, 2, 1)
        self.lineEdit_ThermoOptic = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_ThermoOptic.setObjectName(_fromUtf8("lineEdit_ThermoOptic"))
        self.gridLayout_12.addWidget(self.lineEdit_ThermoOptic, 3, 1, 2, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_6)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_12.addWidget(self.label_13, 5, 0, 2, 1)
        self.lineEdit_tolerance = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_tolerance.setObjectName(_fromUtf8("lineEdit_tolerance"))
        self.gridLayout_12.addWidget(self.lineEdit_tolerance, 5, 1, 2, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_6)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_12.addWidget(self.label_14, 7, 0, 1, 1)
        self.lineEdit_TempThresh = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_TempThresh.setObjectName(_fromUtf8("lineEdit_TempThresh"))
        self.gridLayout_12.addWidget(self.lineEdit_TempThresh, 7, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_6, 1, 4, 6, 1)
        self.checkBox = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_10.addWidget(self.checkBox, 0, 4, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem2, 2, 0, 1, 1)
        self.listWidget_SelectThermocouple = QtGui.QListWidget(self.groupBox_5)
        self.listWidget_SelectThermocouple.setObjectName(_fromUtf8("listWidget_SelectThermocouple"))
        self.gridLayout_10.addWidget(self.listWidget_SelectThermocouple, 1, 3, 6, 1)
        self.radioButton_absolutevalue = QtGui.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_absolutevalue.setFont(font)
        self.radioButton_absolutevalue.setChecked(True)
        self.radioButton_absolutevalue.setObjectName(_fromUtf8("radioButton_absolutevalue"))
        self.gridLayout_10.addWidget(self.radioButton_absolutevalue, 5, 0, 1, 1)
        self.radioButton_wavlengthshift = QtGui.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_wavlengthshift.setFont(font)
        self.radioButton_wavlengthshift.setObjectName(_fromUtf8("radioButton_wavlengthshift"))
        self.gridLayout_10.addWidget(self.radioButton_wavlengthshift, 6, 0, 1, 1)
        self.lineEdit_originalwavelength = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_originalwavelength.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_originalwavelength.setFont(font)
        self.lineEdit_originalwavelength.setObjectName(_fromUtf8("lineEdit_originalwavelength"))
        self.gridLayout_10.addWidget(self.lineEdit_originalwavelength, 6, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_5)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_10.addWidget(self.label_15, 4, 0, 1, 3)
        self.label_16 = QtGui.QLabel(self.groupBox_5)
        self.label_16.setEnabled(False)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_10.addWidget(self.label_16, 6, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.pushButton_ResidualStrainCalc = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_ResidualStrainCalc.setObjectName(_fromUtf8("pushButton_ResidualStrainCalc"))
        self.gridLayout_15.addWidget(self.pushButton_ResidualStrainCalc, 0, 0, 1, 1)
        self.progressBar_residual = QtGui.QProgressBar(self.groupBox_5)
        self.progressBar_residual.setProperty("value", 0)
        self.progressBar_residual.setObjectName(_fromUtf8("progressBar_residual"))
        self.gridLayout_15.addWidget(self.progressBar_residual, 0, 1, 1, 1)
        self.pushButton_ResidualPlot = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_ResidualPlot.setObjectName(_fromUtf8("pushButton_ResidualPlot"))
        self.gridLayout_15.addWidget(self.pushButton_ResidualPlot, 0, 2, 1, 1)
        self.pushButton_ResidualSave = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_ResidualSave.setObjectName(_fromUtf8("pushButton_ResidualSave"))
        self.gridLayout_15.addWidget(self.pushButton_ResidualSave, 0, 4, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem3, 0, 3, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_15, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_5, 3, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtGui.QToolBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionCopyrigth = QtGui.QAction(MainWindow)
        self.actionCopyrigth.setIcon(icon)
        self.actionCopyrigth.setObjectName(_fromUtf8("actionCopyrigth"))
        self.actionExitProgram = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("DESIGN_Resource/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExitProgram.setIcon(icon2)
        self.actionExitProgram.setObjectName(_fromUtf8("actionExitProgram"))
        self.actionAbouttheauthor = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("DESIGN_Resource/author.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbouttheauthor.setIcon(icon3)
        self.actionAbouttheauthor.setObjectName(_fromUtf8("actionAbouttheauthor"))
        self.actionAddFBGFiles = QtGui.QAction(MainWindow)
        self.actionAddFBGFiles.setObjectName(_fromUtf8("actionAddFBGFiles"))
        self.actionAddTempFiles = QtGui.QAction(MainWindow)
        self.actionAddTempFiles.setObjectName(_fromUtf8("actionAddTempFiles"))
        self.actionRemoveFBGfile = QtGui.QAction(MainWindow)
        self.actionRemoveFBGfile.setObjectName(_fromUtf8("actionRemoveFBGfile"))
        self.actionRemoveTempfile = QtGui.QAction(MainWindow)
        self.actionRemoveTempfile.setObjectName(_fromUtf8("actionRemoveTempfile"))
        self.actionFBGClearFiles = QtGui.QAction(MainWindow)
        self.actionFBGClearFiles.setObjectName(_fromUtf8("actionFBGClearFiles"))
        self.actionTempClearFiles = QtGui.QAction(MainWindow)
        self.actionTempClearFiles.setObjectName(_fromUtf8("actionTempClearFiles"))
        self.actionDataSync = QtGui.QAction(MainWindow)
        self.actionDataSync.setObjectName(_fromUtf8("actionDataSync"))
        self.actionSaveSyncData = QtGui.QAction(MainWindow)
        self.actionSaveSyncData.setObjectName(_fromUtf8("actionSaveSyncData"))
        self.actionResidualStrainCalcul = QtGui.QAction(MainWindow)
        self.actionResidualStrainCalcul.setObjectName(_fromUtf8("actionResidualStrainCalcul"))
        self.actionResidualSave = QtGui.QAction(MainWindow)
        self.actionResidualSave.setObjectName(_fromUtf8("actionResidualSave"))
        self.actionPlotResidual = QtGui.QAction(MainWindow)
        self.actionPlotResidual.setObjectName(_fromUtf8("actionPlotResidual"))
        self.actionFilesFormat_FBG = QtGui.QAction(MainWindow)
        self.actionFilesFormat_FBG.setObjectName(_fromUtf8("actionFilesFormat_FBG"))
        self.actionFilesFormat_Term = QtGui.QAction(MainWindow)
        self.actionFilesFormat_Term.setObjectName(_fromUtf8("actionFilesFormat_Term"))
        self.toolBar.addAction(self.actionCopyrigth)
        self.toolBar.addAction(self.actionAbouttheauthor)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExitProgram)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButton_ClearMessageBoard, QtCore.SIGNAL(_fromUtf8("clicked()")), self.MessageBoard.clear)
        QtCore.QObject.connect(self.pushButton_LoadFBGFiles, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionAddFBGFiles.trigger)
        QtCore.QObject.connect(self.pushButton_LoadTempFiles, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionAddTempFiles.trigger)
        QtCore.QObject.connect(self.pushButton_RemoveFBGFiles, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionRemoveFBGfile.trigger)
        QtCore.QObject.connect(self.pushButton_RemoveTempFiles, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionRemoveTempfile.trigger)
        QtCore.QObject.connect(self.pushButton_FBGClearAll, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionFBGClearFiles.trigger)
        QtCore.QObject.connect(self.pushButton_TempClearAll, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionTempClearFiles.trigger)
        QtCore.QObject.connect(self.pushButton_DataSync, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionDataSync.trigger)
        QtCore.QObject.connect(self.pushButton_SaveSyncData, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionSaveSyncData.trigger)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupBox_6.setEnabled)
        QtCore.QObject.connect(self.pushButton_ResidualStrainCalc, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionResidualStrainCalcul.trigger)
        QtCore.QObject.connect(self.radioButton_wavlengthshift, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_16.setEnabled)
        QtCore.QObject.connect(self.radioButton_wavlengthshift, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEdit_originalwavelength.setEnabled)
        QtCore.QObject.connect(self.pushButton_ResidualSave, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionResidualSave.trigger)
        QtCore.QObject.connect(self.pushButton_ResidualPlot, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionPlotResidual.trigger)
        QtCore.QObject.connect(self.pushButton_FilesFormat_FBG, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionFilesFormat_FBG.trigger)
        QtCore.QObject.connect(self.pushButton_FilesFormat_Term, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionFilesFormat_Term.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "FBG_ReStrain V1.0", None))
        self.label.setText(_translate("MainWindow", "Message Board:", None))
        self.pushButton_ClearMessageBoard.setText(_translate("MainWindow", "Clear Message Board", None))
        self.label_64.setText(_translate("MainWindow", "FBG_ReStrain 2016 by Gilmar F. Pereira", None))
        self.label_2.setText(_translate("MainWindow", "FBG_ReStrain - Software to Sync FBG and Thermocouple Data & Calculate Residual Strain", None))
        self.groupBox.setTitle(_translate("MainWindow", "(1) Input (FBG and Thermocouple files)", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Thermocouple Data (*.csv)", None))
        self.comboBox_TempSep.setItemText(0, _translate("MainWindow", "; (default)", None))
        self.comboBox_TempSep.setItemText(1, _translate("MainWindow", "tab", None))
        self.comboBox_TempSep.setItemText(2, _translate("MainWindow", ",", None))
        self.label_7.setText(_translate("MainWindow", "Sep:", None))
        self.pushButton_TempClearAll.setText(_translate("MainWindow", "Clear All", None))
        self.pushButton_RemoveTempFiles.setText(_translate("MainWindow", "Remove File", None))
        self.pushButton_LoadTempFiles.setText(_translate("MainWindow", "Add Files", None))
        self.label_31.setText(_translate("MainWindow", "Skip Row:", None))
        self.label_5.setText(_translate("MainWindow", "Number of Thermocouples:", None))
        self.label_17.setText(_translate("MainWindow", "Time Zone Correction (h)", None))
        self.pushButton_FilesFormat_Term.setText(_translate("MainWindow", "Files Format", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "FBG Data (*.txt)", None))
        self.pushButton_RemoveFBGFiles.setText(_translate("MainWindow", "Remove File", None))
        self.pushButton_LoadFBGFiles.setText(_translate("MainWindow", "Add Files", None))
        self.label_4.setText(_translate("MainWindow", "Number of FBG Sensors:", None))
        self.pushButton_FBGClearAll.setText(_translate("MainWindow", "Clear All", None))
        self.label_30.setText(_translate("MainWindow", "Skip Row:", None))
        self.comboBox_FBGSep.setItemText(0, _translate("MainWindow", "tab (default)", None))
        self.comboBox_FBGSep.setItemText(1, _translate("MainWindow", ";", None))
        self.comboBox_FBGSep.setItemText(2, _translate("MainWindow", ",", None))
        self.label_6.setText(_translate("MainWindow", "Sep:", None))
        self.pushButton_FilesFormat_FBG.setText(_translate("MainWindow", "Files Format", None))
        self.label_3.setText(_translate("MainWindow", "This input interface was developed for the data obtained by: BraggMeter Fibersensing (FBG) and DaqPRO 5300 (Thermocouple)", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "(2) Data Sync", None))
        self.pushButton_DataSync.setText(_translate("MainWindow", "Data Sync.", None))
        self.pushButton_SaveSyncData.setText(_translate("MainWindow", "Save Sync Data", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "(3) Residual Strain Calculation", None))
        self.label_8.setText(_translate("MainWindow", "Select the FBG:", None))
        self.label_9.setText(_translate("MainWindow", "Select the Thermocouple:", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Method Parameters:", None))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400;\">F.O. Photo-elastic coefficient </span>(pe)</p></body></html>", None))
        self.lineEdit_PhotoElastic.setText(_translate("MainWindow", "0.22", None))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400;\">F.O. Thermal-Expansion coefficient </span>(<span style=\" font-family:\'Calibri,sans-serif\'; font-size:11pt;\">α</span>)</p></body></html>", None))
        self.lineEdit_ThermalExpansion.setText(_translate("MainWindow", "4.0E-6", None))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400;\">F.O. Thermo-optic coefficient</span> (ξ )</p></body></html>", None))
        self.lineEdit_ThermoOptic.setText(_translate("MainWindow", "0.55E-6", None))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p>Gel-Point tolerance (Strain)</p></body></html>", None))
        self.lineEdit_tolerance.setText(_translate("MainWindow", "0.0001", None))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p>Temperature threshold (<span style=\" vertical-align:super;\">o</span>C)</p></body></html>", None))
        self.lineEdit_TempThresh.setText(_translate("MainWindow", "25.0", None))
        self.checkBox.setText(_translate("MainWindow", "Advanced Mode", None))
        self.radioButton_absolutevalue.setText(_translate("MainWindow", "Absolute value", None))
        self.radioButton_wavlengthshift.setText(_translate("MainWindow", "Wavelength shift", None))
        self.lineEdit_originalwavelength.setText(_translate("MainWindow", "1550.0", None))
        self.label_15.setText(_translate("MainWindow", "FBG Data format:", None))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400;\">Original</span> λ<span style=\" vertical-align:sub;\">0</span></p></body></html>", None))
        self.pushButton_ResidualStrainCalc.setText(_translate("MainWindow", "(4) Residual Strain Calculation", None))
        self.pushButton_ResidualPlot.setText(_translate("MainWindow", "Plot", None))
        self.pushButton_ResidualSave.setText(_translate("MainWindow", "Save Data (*CSV)", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionCopyrigth.setText(_translate("MainWindow", "About the FBG_ReStrain/Copyrigth", None))
        self.actionCopyrigth.setToolTip(_translate("MainWindow", "Software information and Copyrigth", None))
        self.actionExitProgram.setText(_translate("MainWindow", "Exit Program", None))
        self.actionExitProgram.setToolTip(_translate("MainWindow", "Exit Program (the data is not saved)", None))
        self.actionAbouttheauthor.setText(_translate("MainWindow", "About the Author", None))
        self.actionAbouttheauthor.setToolTip(_translate("MainWindow", "Information about the FBG_SiMul author", None))
        self.actionAddFBGFiles.setText(_translate("MainWindow", "AddFBGFiles", None))
        self.actionAddTempFiles.setText(_translate("MainWindow", "AddTempFiles", None))
        self.actionRemoveFBGfile.setText(_translate("MainWindow", "RemoveFBGfile", None))
        self.actionRemoveTempfile.setText(_translate("MainWindow", "RemoveTempfile", None))
        self.actionFBGClearFiles.setText(_translate("MainWindow", "FBGClearFiles", None))
        self.actionTempClearFiles.setText(_translate("MainWindow", "TempClearFiles", None))
        self.actionDataSync.setText(_translate("MainWindow", "DataSync", None))
        self.actionSaveSyncData.setText(_translate("MainWindow", "SaveSyncData", None))
        self.actionResidualStrainCalcul.setText(_translate("MainWindow", "ResidualStrainCalcul", None))
        self.actionResidualSave.setText(_translate("MainWindow", "ResidualSave", None))
        self.actionPlotResidual.setText(_translate("MainWindow", "PlotResidual", None))
        self.actionFilesFormat_FBG.setText(_translate("MainWindow", "FilesFormat_FBG", None))
        self.actionFilesFormat_Term.setText(_translate("MainWindow", "FilesFormat_Term", None))

